version: 2
jobs:
  build:
    docker:
      - image: circleci/golang:latest
    working_directory: /go/src/github.com/koron/dbquerylog
    steps:
      - checkout
      - run:
          name: Check golang environment
          command: go env
      - run:
          name: Install dependencies
          command: go get -v -t -d ./...
      - run:
          name: Test all
          command: go test -v ./...
      - run:
          name: Build
          command: go build -v .
